site:
  title: "FCB Software"
  description: "Criamos sistemas, plataformas web e APIs pensados para resolver problemas reais de negócio, automatizar processos e impulsionar resultados. Nosso compromisso é transformar ideias em software robusto, confiável e pronto para crescer junto com sua empresa."
  based: "Schoroeder, SC"
  timezone: "America/Sao_Paulo"
  locale: "pt-BR"